CREATE TABLE "users" (
  "user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL UNIQUE,
  "password" varchar(255) NOT NULL,
  "role" varchar(255) NOT NULL
);

CREATE TABLE "companies" (
  "company_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_name" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "address" varchar(255) NOT NULL,
  "contact_number" varchar(255) NOT NULL,
  "state" varchar(255) NOT NULL,
  "gst_no" varchar(255) NOT NULL,
  "financial_year_start" date NOT NULL,
  "financial_year_end" date NOT NULL
);
CREATE TABLE "company_users" (
  "company_user_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "user_id" integer NOT NULL,
  "company_id" integer NOT NULL,
  "role" varchar(20) NOT NULL,
  FOREIGN KEY ("user_id") REFERENCES "users"("user_id"),
  FOREIGN KEY ("company_id") REFERENCES "companies"("company_id"),
  UNIQUE ("user_id", "company_id")
);
CREATE TABLE "customers" (
  "customer_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "contact_no" varchar(255) NOT NULL
);

CREATE TABLE "suppliers" (
  "supplier_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "name" varchar(255) NOT NULL,
  "contact_no" varchar(255) NOT NULL,
  "email" varchar(255) NOT NULL,
  "address" varchar(255) NOT NULL,
  "gst_no" varchar(255) NOT NULL
);

CREATE TABLE "items" (
  "item_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "item_name" varchar(255) NOT NULL,
  "sku" varchar(255) NOT NULL,
  "brand" varchar(255) NOT NULL,
  "category_id" integer NOT NULL,
  "unit_id" integer NOT NULL,
  "gst_percentage" numeric NOT NULL,
  "default_purchase_price" numeric NOT NULL,
  "default_selling_price" numeric NOT NULL,
  "current_quantity" integer NOT NULL,
  "status" varchar(255) NOT NULL
);

CREATE TABLE "purchase_voucher" (
  "voucher_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "supplier_id" integer NOT NULL,
  "date" date NOT NULL,
  "total_amt" numeric NOT NULL
);

CREATE TABLE "purchase_voucher_items" (
  "voucher_items_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "voucher_id" integer NOT NULL,
  "item_id" integer NOT NULL,
  "qty" integer NOT NULL,
  "total_amt" numeric NOT NULL
);

CREATE TABLE "sales_voucher" (
  "sales_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "total_amt" numeric NOT NULL,
  "date" date NOT NULL
);

CREATE TABLE "sales_voucher_items" (
  "sales_items_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "sales_id" integer NOT NULL,
  "item_id" integer NOT NULL,
  "qty" integer NOT NULL,
  "total_amt" numeric NOT NULL
);

CREATE TABLE "payment_voucher" (
  "payment_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "supplier_id" integer NOT NULL,
  "voucher_id" integer NOT NULL,
  "amount_paid" numeric NOT NULL,
  "date" date NOT NULL,
  "mode" varchar(255) NOT NULL
);

CREATE TABLE "receipt_vouchers" (
  "receipt_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "company_id" integer NOT NULL,
  "customer_id" integer NOT NULL,
  "sales_id" integer NOT NULL,
  "amount_paid" numeric NOT NULL,
  "date" date NOT NULL,
  "mode" varchar(255) NOT NULL
);

CREATE TABLE "categories" (
  "category_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "category_name" varchar(255) NOT NULL
);

CREATE TABLE "units" (
  "unit_id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY NOT NULL,
  "unit_name" varchar(255) NOT NULL
);


ALTER TABLE "customers" ADD CONSTRAINT "fk_companies_company_id_customers" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "suppliers" ADD CONSTRAINT "fk_companies_company_id_suppliers" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "items" ADD CONSTRAINT "fk_companies_company_id_iteams" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_voucher" ADD CONSTRAINT "fk_companies_company_id_purchase_voucher" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_voucher" ADD CONSTRAINT "fk_purchase_voucher_supplier_id(fk)_suppliers" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_voucher_items" ADD CONSTRAINT "fk_purchase_voucher_items_voucher_id(fk)_purchase_voucher" FOREIGN KEY ("voucher_id") REFERENCES "purchase_voucher" ("voucher_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales_voucher" ADD CONSTRAINT "fk_companies_company_id_sales_voucher" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales_voucher" ADD CONSTRAINT "fk_customers_customer_id_sales_voucher" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales_voucher_items" ADD CONSTRAINT "fk_sales_voucher_sales_id_sales_voucher_iteams" FOREIGN KEY ("sales_id") REFERENCES "sales_voucher" ("sales_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_voucher" ADD CONSTRAINT "fk_payment_voucher_company_id(fk)_companies" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_voucher" ADD CONSTRAINT "fk_suppliers_supplier_id_payment_voucher" FOREIGN KEY ("supplier_id") REFERENCES "suppliers" ("supplier_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "payment_voucher" ADD CONSTRAINT "fk_purchase_voucher_voucher_id_payment_voucher" FOREIGN KEY ("voucher_id") REFERENCES "purchase_voucher" ("voucher_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receipt_vouchers" ADD CONSTRAINT "fk_companies_company_id_receipt_vouchers" FOREIGN KEY ("company_id") REFERENCES "companies" ("company_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receipt_vouchers" ADD CONSTRAINT "fk_customers_customer_id_receipt_vouchers" FOREIGN KEY ("customer_id") REFERENCES "customers" ("customer_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "receipt_vouchers" ADD CONSTRAINT "fk_sales_voucher_sales_id_receipt_vouchers" FOREIGN KEY ("sales_id") REFERENCES "sales_voucher" ("sales_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "items" ADD CONSTRAINT "fk_categories_category_id_iteams" FOREIGN KEY ("category_id") REFERENCES "categories" ("category_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "items" ADD CONSTRAINT "fk_units_unit_id_iteams" FOREIGN KEY ("unit_id") REFERENCES "units" ("unit_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "purchase_voucher_items" ADD CONSTRAINT "fk_items_item_id_purchase_voucher_items" FOREIGN KEY ("item_id") REFERENCES "items" ("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sales_voucher_items" ADD CONSTRAINT "fk_sales_voucher_items_iteam_id(fk)_items" FOREIGN KEY ("item_id") REFERENCES "items" ("item_id") ON DELETE NO ACTION ON UPDATE NO ACTION DEFERRABLE INITIALLY IMMEDIATE;
